"""empty message

Revision ID: 26110289b7a1
Revises: 34c0ad6c59a1
Create Date: 2021-04-02 23:34:40.463871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26110289b7a1'
down_revision = '34c0ad6c59a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('following', sa.Column('company', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('following', 'company')
    # ### end Alembic commands ###
