"""empty message

Revision ID: 2d484f80e7da
Revises: b129a39d0308
Create Date: 2021-03-30 00:00:33.661594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d484f80e7da'
down_revision = 'b129a39d0308'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'client_info', ['tel'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'client_info', type_='unique')
    # ### end Alembic commands ###
