"""empty message

Revision ID: 34c0ad6c59a1
Revises: 37d711818dbe
Create Date: 2021-04-02 19:28:48.703252

"""
from alembic import op
import sqlalchemy as sa
from models import FollowStatusChoices
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '34c0ad6c59a1'
down_revision = '37d711818dbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('following', sa.Column('status', sqlalchemy_utils.types.choice.ChoiceType(FollowStatusChoices), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('following', 'status')
    # ### end Alembic commands ###
