"""empty message

Revision ID: 37d711818dbe
Revises: 93bdb9723382
Create Date: 2021-04-02 19:27:50.250411

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '37d711818dbe'
down_revision = '93bdb9723382'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('following', 'status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('following', sa.Column('status', mysql.VARCHAR(length=255), nullable=True))
    # ### end Alembic commands ###
