"""empty message

Revision ID: 6711b83c944e
Revises: 549b2437bed2
Create Date: 2021-04-22 16:55:59.181656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6711b83c944e'
down_revision = '549b2437bed2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('following', sa.Column('address', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('following', 'address')
    # ### end Alembic commands ###
