"""empty message

Revision ID: 6cde5e31937c
Revises: ef0774477982
Create Date: 2021-04-02 18:45:17.462781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cde5e31937c'
down_revision = 'ef0774477982'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('following', sa.Column('name', sa.String(length=100), nullable=True))
    op.add_column('following', sa.Column('tel', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('following', 'tel')
    op.drop_column('following', 'name')
    # ### end Alembic commands ###
