"""empty message

Revision ID: 6fa5d6e0ea3f
Revises: 9d78de0ec61c
Create Date: 2021-04-22 14:48:52.728021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fa5d6e0ea3f'
down_revision = '9d78de0ec61c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('following', sa.Column('feedback', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('following', 'feedback')
    # ### end Alembic commands ###
