"""empty message

Revision ID: 93bdb9723382
Revises: 32e4a957e8d3
Create Date: 2021-04-02 19:07:45.543783

"""
from alembic import op
import sqlalchemy as sa
from models import Following
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '93bdb9723382'
down_revision = '32e4a957e8d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('following', sa.Column('status', sqlalchemy_utils.types.choice.ChoiceType(Following.STATUS_CHOICES), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('following', 'status')
    # ### end Alembic commands ###
