"""empty message

Revision ID: ac8a919947e5
Revises: 1101d2a0c0ee
Create Date: 2021-04-03 21:16:19.312898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac8a919947e5'
down_revision = '1101d2a0c0ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('following', sa.Column('follower_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'following', 'seller', ['follower_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'following', type_='foreignkey')
    op.drop_column('following', 'follower_id')
    # ### end Alembic commands ###
