"""empty message

Revision ID: b129a39d0308
Revises: e75c91df25e1
Create Date: 2021-03-29 22:36:15.855147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b129a39d0308'
down_revision = 'e75c91df25e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('tel', table_name='client_info')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('tel', 'client_info', ['tel'], unique=True)
    # ### end Alembic commands ###
