"""empty message

Revision ID: b32641f42b7c
Revises: 6cde5e31937c
Create Date: 2021-04-02 18:56:00.790873

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b32641f42b7c'
down_revision = '6cde5e31937c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('following', 'status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('following', sa.Column('status', mysql.VARCHAR(length=255), nullable=True))
    # ### end Alembic commands ###
