"""empty message

Revision ID: b7241515231f
Revises: b32641f42b7c
Create Date: 2021-04-02 18:56:58.373187

"""
from alembic import op
from models import Following
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'b7241515231f'
down_revision = 'b32641f42b7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('following', sa.Column('status', sqlalchemy_utils.types.choice.ChoiceType(Following.STATUS_CHOICES), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('following', 'status')
    # ### end Alembic commands ###
