"""empty message

Revision ID: e21025525f17
Revises: 2d484f80e7da
Create Date: 2021-04-02 12:54:25.609471

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from models import Following


# revision identifiers, used by Alembic.
revision = 'e21025525f17'
down_revision = '2d484f80e7da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('following',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status', sqlalchemy_utils.types.choice.ChoiceType(Following.STATUS_CHOICES), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seller',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('tel', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('seller')
    op.drop_table('following')
    # ### end Alembic commands ###
