"""empty message

Revision ID: e75c91df25e1
Revises: 22e308116a3f
Create Date: 2021-03-29 15:03:20.537865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e75c91df25e1'
down_revision = '22e308116a3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'client_info', ['tel'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'client_info', type_='unique')
    # ### end Alembic commands ###
