"""empty message

Revision ID: ef0774477982
Revises: e21025525f17
Create Date: 2021-04-02 15:41:16.885319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef0774477982'
down_revision = 'e21025525f17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'seller', ['name'])
    op.create_unique_constraint(None, 'seller', ['tel'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'seller', type_='unique')
    op.drop_constraint(None, 'seller', type_='unique')
    # ### end Alembic commands ###
