"""empty message

Revision ID: f97c6b84fbf5
Revises: 
Create Date: 2021-04-22 23:29:36.808562

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f97c6b84fbf5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tags_map',
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.Column('following_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['following_id'], ['following.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], )
    )
    op.add_column('following', sa.Column('address', sa.String(length=255), nullable=True))
    op.add_column('following', sa.Column('download', sa.Boolean(), nullable=True))
    op.add_column('following', sa.Column('markup', sa.String(length=200), nullable=True))
    op.alter_column('following', 'created_at',
               existing_type=mysql.DATETIME(),
               comment='创建时间',
               existing_comment='????',
               existing_nullable=True)
    op.alter_column('following', 'updated_at',
               existing_type=mysql.DATETIME(),
               comment='更新时间',
               existing_comment='????',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('following', 'updated_at',
               existing_type=mysql.DATETIME(),
               comment='????',
               existing_comment='更新时间',
               existing_nullable=True)
    op.alter_column('following', 'created_at',
               existing_type=mysql.DATETIME(),
               comment='????',
               existing_comment='创建时间',
               existing_nullable=True)
    op.drop_column('following', 'markup')
    op.drop_column('following', 'download')
    op.drop_column('following', 'address')
    op.drop_table('tags_map')
    op.drop_table('tag')
    # ### end Alembic commands ###
